auto_save: true
default_run: '01'
default_session: '001'
default_subject: '01'
directory:
  derivatives_dir: derivatives
  processed_dir: data/processed
  raw_data_dir: data/pilot_data/tasks
  reports_dir: reports/advanced
  root: ./
file_path_pattern: sub-01_ses-001_task-gng_image_run-01_raw.fif
pipeline:
  steps:
  - name: LoadData
    params:
      input_file: null
  - name: PrepChannelsStep
    params:
      channel_types:
        "X1:ECG": ecg
      on_missing: ignore
  - name: FilterStep
    params:
      h_freq: 40.0
      l_freq: 1.0
      notch_freqs:
      - 50
      - 60
  - name: EpochingStep
    params:
      task_type: custom
      trigger_ids:
        go: 1
        nogo: 2
      epoch_params:
        tmin: -0.2
        tmax: 1.0
        baseline: [null, 0]
      stim_channel: Trigger
      returns_epochs: true
  - name: AutoRejectStep
    params:
      flat:
        eeg: 1.0e-06
      reject:
        ecg: 0.0005
        eeg: 0.0001
  - name: ICAStep
    params:
      ecg_threshold: 3.0
      eog_threshold: 3.0
      exclude: []
      fit_params:
        extended: true
      interactive: true
      manual_selection: true
      method: infomax
      n_components: 0.99
      plot_components: true
      plot_properties: true
      plot_sources: true
      use_good_epochs_only: true
  - name: EpochingStep
    params:
      task_type: custom
      trigger_ids:
        go: 1
        nogo: 2
      epoch_params:
        tmin: -0.2
        tmax: 1.0
        baseline: [null, 0]
      stim_channel: Trigger
      returns_epochs: true
  - name: AutoRejectStep
    params:
      flat:
        eeg: 1.0e-06
      reject:
        ecg: 0.0005
        eeg: 0.0001
  - name: SaveCheckpoint
    params:
      checkpoint_key: after_autoreject
pipeline_mode: standard
