## Go/No-Go analysis example
# Optional specialized steps are registered conditionally (see scr/steps/__init__.py).
# Prerequisite: run minimal preprocessing first (e.g., configs/gonogo_minimal_pipeline.json)
# to generate a preprocessed FIF. Expected naming:
#   data/processed/sub-<id>/ses-<id>/sub-<id>_ses-<id>_task-gng_raw.fif

auto_save: false
default_subject: "01"
default_session: "001"
default_run: "01"
directory:
  root: "."
  raw_data_dir: "data/pilot_data"
  processed_dir: "data/processed"
  reports_dir: "reports/analysis"
  derivatives_dir: "derivatives"

pipeline_mode: "standard"

pipeline:
  steps:
    - name: LoadData
      params:
        input_file: "data/processed/sub-01/ses-001/sub-01_ses-001_task-gng_raw.fif"  # adjust as needed

    - name: FilterStep
      params:
        l_freq: 1
        h_freq: 30

    - name: GoNoGoTriggerStep
      params:
        stim_channel: "Trigger"

    - name: GoNoGoEpochingStep
      params:
        tmin: -0.2
        tmax: 0.8
        baseline: [null, 0]

    - name: SaveData
      params:
        output_path: "data/processed/sub-01/ses-001/sub-01_ses-001_task-gng_desc-correct-epo.fif"
        overwrite: true
