pipeline:
  # <--- NEW: signals multi-subject logic in pipeline.py
  multi_subject: true
  
  steps:
    - name: LoadData
      params:
        file_path_pattern: "data/pilot_data/sub-*_ses-*_raw.edf"

    - name: PrepChannelsStep

    - name: FilterStep
      params:
        l_freq: 1
        h_freq: 100
        notch_freqs: [60, 120]

    - name: AutoRejectStep
      params:
        ar_params:
          consensus: null
          n_interpolate: null
          random_state: null
          thresh_method: 'bayesian_optimization'
        store_log: true

    - name: SaveCheckpoint
      params:
        # Will be dynamically rewritten to sub-X/ses-Y in pipeline.py
        output_path: "data/pilot_data/after_autoreject.fif"
        overwrite: true

    - name: ICAStep
      params:
        n_components: 0.99
        method: 'infomax'
        max_iter: 2000
        fit_params:
          extended: true
          l_rate: 0.001
        decim: 3
        use_good_epochs_only: true
        eog_ch_names: ['Fp1', 'Fp2']
        eog_threshold: 0.5
        ecg_channel: null
        ecg_threshold: 0.3
        exclude: []
        plot_dir: "reports/ica"        # Will also be dynamically rewritten
        interactive: true
        plot_components: true
        plot_sources: true

    - name: SaveData
      params:
        # Will be updated with sub-XX/ses-YY automatically
        output_path: "data/pilot_data/raw_preprocessed.fif"
        overwrite: true

    - name: SplitTasksStep
      params:
        # same approach if you want them in sub-XX/ses-YY
        output_folder: "data/pilot_data/tasks"
        tasks:
          - name: "Rest_GoNoGo"
            start_trigger: 6
            end_trigger: 7
          - name: "GoNoGo"
            start_trigger: 7
            end_trigger: 9
          - name: "MentalImagery"
            start_trigger: 8
            end_trigger: 9
            occurrence_index: 2
          - name: "LandoitC"
            start_after_task: "GoNoGo"
            start_offset_minutes: 14
            end_before_trigger: 6
            end_offset_minutes: 1
