# File: eeg_pipeline/configs/pilot_preprocessing_strategy.yml

pipeline:
  steps:
    - name: LoadData
      params:
        file_path: "D:/Yann/neuropipe/data/pilot_data/sub-01_ses-001_raw.edf"

    - name: PrepChannelsStep
      # no special params needed unless you want to override channel lists

    - name: FilterStep
      params:
        l_freq: 1
        h_freq: 100
        notch_freqs: [60, 120]

    - name: AutoRejectStep
      params:
        ar_params:
          consensus: None
          n_interpolate: None
          random_state: None
          thresh_method: 'bayesian_optimization'
        store_log: true

    - name: SaveCheckpoint  
      params:
        output_path: "data/pilot_data/sub-01_ses-001_after_autoreject.fif"
        overwrite: true

    - name: ICAStep
      params:
        n_components: 0.95
        random_state: 42
        decim: 3
        use_eog_detection: false
        eog_ch_name: []
        plot_components: true
        plot_sources: false
        interactive: true
        exclude: []

    - name: SaveData
      params:
        output_path: "data/pilot_data/sub-01_ses-001_raw_preprocessed.fif"
        overwrite: true

    - name: SplitTasksStep
      params:
        # Where to save each sub-task .fif
        output_folder: "data/pilot_data/"
