directory:
  root: "E:/Yann/neuropipe/"
  raw_data_dir: "data/raw"
  processed_dir: "data/processed"
  reports_dir: "reports"
  derivatives_dir: "derivatives"

default_subject: "sub-01" 
default_session: "ses-001"
default_run: "01"

pipeline:
  multi_subject: true
  
  steps:
    - name: LoadData
      params:
        file_path_pattern: "sub-*_ses-*_raw.edf"

    - name: PrepChannelsStep

    - name: FilterStep
      params:
        l_freq: 1
        h_freq: 100
        notch_freqs: [60, 120]

    - name: AutoRejectStep
      params:
        ar_params:
          consensus: null
          n_interpolate: null
          random_state: null
          thresh_method: 'bayesian_optimization'
        store_log: true

    - name: SaveCheckpoint
      params:
        checkpoint_key: "after_autoreject"
        overwrite: true

    # - name: ICAStep
    #   params:
    #     n_components: 0.99
    #     method: 'infomax'
    #     max_iter: 2000
    #     fit_params:
    #       extended: true
    #       l_rate: 0.001
    #     decim: 3
    #     use_good_epochs_only: true
    #     eog_ch_names: [] #['Fp1', 'Fp2']
    #     eog_threshold: 0.5
    #     ecg_channel: null
    #     ecg_threshold: 0.3
    #     exclude: [1,2,6]
    #     plot_dir: "reports/ica"        # Will also be dynamically rewritten
    #     interactive: false
    #     plot_components: false
    #     plot_sources: false

    - name: SplitTasksStep
      params:
        tasks:

          - name: "rest"
            start_trigger: 6
            end_trigger: 7

          - name: "gng_image"
            start_trigger: 7
            end_trigger: 9

          - name: "mental_imagery"
            start_trigger: 8
            end_trigger: 9
            occurrence_index: 2

          - name: "landoitc"
            start_after_task: "gng_image"
            start_offset_minutes: 14
            end_before_trigger: 6
            end_before_occurrence_index: 2
            end_offset_minutes: 1


