# File: neuropipe/configs/pilot_preprocessing_strategy.yml

pipeline:
  steps:
    - name: LoadData
      params:
        file_path: "data/pilot_data/sub-01_ses-001_raw.edf"

    - name: PrepChannelsStep

    - name: FilterStep
      params:
        l_freq: 1
        h_freq: 100
        notch_freqs: [60, 120]

    - name: AutoRejectStep
      params:
        ar_params:
          consensus: null
          n_interpolate: null
          random_state: null
          thresh_method: 'bayesian_optimization'
        store_log: true

    - name: SaveCheckpoint
      params:
        output_path: "data/pilot_data/sub-01_ses-001_after_autoreject.fif"
        overwrite: true

    - name: ICAStep
      params:
        # Keep ~99% of variance
        n_components: 0.99
        method: 'infomax'
        max_iter: 2000
        fit_params:
          extended: true
          l_rate: 0.001
        
        decim: 3
        use_good_epochs_only: true

        # We do EOG detection on Fp1/Fp2, but won't automatically exclude
        eog_ch_names: ['Fp1', 'Fp2']
        eog_threshold: 0.5

        # ECG is optional if we have a channel, otherwise it's disabled
        ecg_channel: null
        ecg_threshold: 0.3

        # We won't auto-exclude anything. 
        # Instead, we simply log suggestions & let the user decide.
        exclude: []   # any components you already know to exclude
        plot_dir: "../reports/ica"
        interactive: true
        plot_components: true
        plot_sources: true

    - name: SaveData
      params:
        output_path: "data/pilot_data/sub-01_ses-001_raw_preprocessed.fif"
        overwrite: true

    - name: SplitTasksStep
      params:
        output_folder: "data/pilot_data/tasks"
        tasks:
          - name: "Rest_GoNoGo"
            start_trigger: 6
            end_trigger: 7
          - name: "GoNoGo"
            start_trigger: 7
            end_trigger: 9
          - name: "MentalImagery"
            start_trigger: 8
            end_trigger: 9
            occurrence_index: 2  # second occurrence
          - name: "LandoitC"
            start_after_task: "GoNoGo"
            start_offset_minutes: 14
            end_before_trigger: 6
            end_offset_minutes: 1